version: "3.7"
services:

  gateway:
    build:
      context: gateway
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - backend-nginx

  frontend:
    build:
      context: frontend/docker/development/nginx
    volumes:
      - "./frontend/public/dist:/app/public"

  backend-nginx:
    build:
      context: backend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./backend/public:/app/public
    depends_on:
      - backend-php-fpm

  backend-php-fpm:
    build:
      context: backend/docker
      dockerfile: development/php-fpm/Dockerfile
    environment:
      APP_DEBUG: 1
      APP_ENV: dev
      DB_HOST: backend-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
    volumes:
      - ./backend/public:/app/public

  backend-php-cli:
    build:
      context: backend/docker
      dockerfile: development/php-cli/Dockerfile
    environment:
      APP_DEBUG: 1
      APP_ENV: dev
      DB_HOST: backend-postgres
      DB_USER: app
      DB_PASSWORD: secret
      DB_NAME: app
    volumes:
      - ./backend/public:/app

  backend-postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRESS_DB: app
    volumes:
      - backend-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  backend-postgres: