version: "3.7"
services:

  gateway:
    build:
      context: gateway/development/nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - backend-nginx

  frontend:
    build:
      context: frontend/docker/development/nginx
    volumes:
      - "./frontend/public/dist:/app/public"

  backend-nginx:
    build:
      context: ./backend/docker/development/nginx
    volumes:
      - ./backend/public:/app/public
    depends_on:
      - backend-php-fpm

  backend-php-fpm:
    build:
      context: backend/docker/development/php-fpm
    volumes:
      - ./backend/public:/app/public