version: "3.7"
services:
  gateway:
    image: ${REGISTRY}/radioavionica-gateway:${IMAGE_TAG}
    restart: always
    volumes:
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend-nginx

  frontend:
    image: ${REGISTRY}/radioavionica-frontend:${IMAGE_TAG}
    restart: always

  backend-nginx:
    image: ${REGISTRY}/radioavionica-backend-nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - backend-php-fpm

  backend-php-fpm:
    image: ${REGISTRY}/radioavionica-backend-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_DEBUG: 1
      APP_ENV: prod
      DB_HOST: backend-postgres
      DB_USER: app
      DB_PASSWORD: $P{RADIOAVIONICA_DB_PASS}
      DB_NAME: app

  backend-php-cli:
    image: ${REGISTRY}/radioavionica-backend-php-cli:${IMAGE_TAG}
    environment:
      APP_DEBUG: 1
      APP_ENV: prod
      DB_HOST: backend-postgres
      DB_USER: app
      DB_PASSWORD: $P{RADIOAVIONICA_DB_PASS}
      DB_NAME: app

  backend-postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: $P{RADIOAVIONICA_DB_PASS}
      POSTGRESS_DB: app
    volumes:
      - backend-postgres:/var/lib/postgresql/data

volumes:
  backend-postgres: